from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^about_trust/$', views.about_trust, name='about_trust'),
    url(r'^about_bhattar/$', views.about_bhattar, name='about_bhattar'),
    url(r'^gurukulam/$', views.gurukulam, name='gurukulam'),
    url(r'^kainkariyam/$', views.kainkariyam, name='kainkariyam'),
    url(r'^library/$', views.library, name='library'),
    url(r'^fb/$', views.fb, name='feedback'),
    url(r'^log/$', views.log, name='log'),
    url(r'^save/$', views.SaveProfile, name='SaveProfile'),
    url(r'^upload/$', views.adminup, name='adminup'),
    url(r'^uplod/(?P<name>\w+)/$', views.adup, name='adup'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^login/$', views.login, name='login'),
    url(r'^done/$', views.payment_done, name='payment_done'),
    url(r'^cancelled/$', views.payment_cancelled, name='payment_cancelled'),
    url(r'^checkout/(?P<name>\w+)/$', views.checkout, name='checkout'),
    url(r'^process/$', views.payment_process, name='process'),
    url(r'^page/(?P<name>\w+)/$', views.page, name='page'),
    url(r'^donar/$', views.donar, name='donar'),
    url(r'^test/$', views.tests, name='tests'),
    url(r'^link/$', views.link, name='link'),
    url(r'^courses/$', views.courses, name='courses'),
    url(r'^jbs/$', views.jbs, name='jbs'),
    # url(r'^job/$',views.job,name='job'),
    url(r'^jbs1/$', views.jbs1, name='jbs1'),
    url(r'^sub/$', views.sub, name='sub'),
    url(r'^crime/$', views.crime, name='crime'),
    url(r'^red/$', views.red, name='red'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^than/$', views.than, name='than'),
    url(r'^events/(?P<id>\d+)$', views.events, name='events'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^Updatedata/$', views.Updatedata, name='Updatedata'),
    url(r'^Update/$', views.Update, name='Update'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^events/$', views.events, name='events'),
    url(r'^archives/$', views.archives, name='archives'),
    url(r'^archives1/$', views.archives1, name='archives1'),
    url(r'^archiv/$', views.archupload, name='archiv'),
    url(r'^jobupload/$', views.jobupload, name='jobupload'),
    url(r'^archivesearch/$',views.archivesearch,name='archivesearch'),

]
