# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homer1c3b'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeR2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('links', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'home_r2',
                'managed': False,
            },
        ),
    ]
