# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-10 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190109_1911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='library',
            table='library',
        ),
    ]
