# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-11 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_admin_feedback_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_on', models.DateTimeField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'adminupload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reference',
                'managed': False,
            },
        ),
    ]
