# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_adminupload_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
