# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/archive/')),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_on', models.DateField()),
                ('active', models.IntegerField(db_column='Active')),
            ],
            options={
                'db_table': 'archive_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('updated_on', models.DateField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'archives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('education_qualification', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('residential_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'donar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('contactno', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eventdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('education_qualification', models.CharField(max_length=200)),
                ('contactnumber', models.IntegerField()),
                ('postapplied', models.CharField(max_length=100)),
                ('upload', models.TextField()),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('updated_on', models.DateField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'job1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('send_via', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='demo',
            name='reference_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demo',
            name='link',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
